//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanUploader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class URL : global::System.Configuration.ApplicationSettingsBase {
        
        private static URL defaultInstance = ((URL)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new URL())));
        
        public static URL Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.219.95.85/prod-api/auth/login")]
        public string httpLogin {
            get {
                return ((string)(this["httpLogin"]));
            }
            set {
                this["httpLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.219.95.85/prod-api/mes/machine/api/machineToMes/chemicalScanSourceVehic" +
            "le")]
        public string scanContainerOut {
            get {
                return ((string)(this["scanContainerOut"]));
            }
            set {
                this["scanContainerOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.219.95.85/prod-api/mes/machine/api/machineToMes/chemicalScanSn")]
        public string scanSn {
            get {
                return ((string)(this["scanSn"]));
            }
            set {
                this["scanSn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.219.95.85/prod-api/mes/machine/api/machineToMes/chemicalScanTargetVehic" +
            "le")]
        public string scanContainerIn {
            get {
                return ((string)(this["scanContainerIn"]));
            }
            set {
                this["scanContainerIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.219.95.85/prod-api/mes/machine/api/machineToMes/chemicalScanSourceVehic" +
            "leUnBind")]
        public string scanContainerUnbind {
            get {
                return ((string)(this["scanContainerUnbind"]));
            }
            set {
                this["scanContainerUnbind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.219.95.85/prod-api/mes/machine/api/machineToMes/chemicalScanSubmit")]
        public string submit {
            get {
                return ((string)(this["submit"]));
            }
            set {
                this["submit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.219.95.85/prod-api/mes/machine/api/machineToMes/getMesMoListByProductMo" +
            "delAndOperation")]
        public string getMesMoList {
            get {
                return ((string)(this["getMesMoList"]));
            }
            set {
                this["getMesMoList"] = value;
            }
        }
    }
}
