//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemicalScan.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class URL : global::System.Configuration.ApplicationSettingsBase {
        
        private static URL defaultInstance = ((URL)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new URL())));
        
        public static URL Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.219.95.85/prod-api/")]
        public string prefix {
            get {
                return ((string)(this["prefix"]));
            }
            set {
                this["prefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.219.196.41/stage-api/auth/login")]
        public string httpLogin_MES {
            get {
                return ((string)(this["httpLogin_MES"]));
            }
            set {
                this["httpLogin_MES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mes/machine/api/machineToMes/")]
        public string subPrefix_MES {
            get {
                return ((string)(this["subPrefix_MES"]));
            }
            set {
                this["subPrefix_MES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chemicalScanSourceVehicle")]
        public string postfix_scanContainerOut {
            get {
                return ((string)(this["postfix_scanContainerOut"]));
            }
            set {
                this["postfix_scanContainerOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chemicalScanSn")]
        public string postfix_scanSn {
            get {
                return ((string)(this["postfix_scanSn"]));
            }
            set {
                this["postfix_scanSn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chemicalScanTargetVehicle")]
        public string postfix_scanContainerIn {
            get {
                return ((string)(this["postfix_scanContainerIn"]));
            }
            set {
                this["postfix_scanContainerIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chemicalScanSourceVehicleUnBind")]
        public string postfix_scanContainerUnbind {
            get {
                return ((string)(this["postfix_scanContainerUnbind"]));
            }
            set {
                this["postfix_scanContainerUnbind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chemicalScanSubmit")]
        public string postfix_submit {
            get {
                return ((string)(this["postfix_submit"]));
            }
            set {
                this["postfix_submit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.210.192.31/stage-api/auth/login")]
        public string httpLogin_WMS {
            get {
                return ((string)(this["httpLogin_WMS"]));
            }
            set {
                this["httpLogin_WMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.210.192.31/stage-api/process/mes/stock/query")]
        public string stockQuery_WMS {
            get {
                return ((string)(this["stockQuery_WMS"]));
            }
            set {
                this["stockQuery_WMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.210.192.31/stage-api/process/mesUpperMaterialRecord/public/mes/validate" +
            "")]
        public string validate_WMS {
            get {
                return ((string)(this["validate_WMS"]));
            }
            set {
                this["validate_WMS"] = value;
            }
        }
    }
}
