//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanUploader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class UserData : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserData defaultInstance = ((UserData)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserData())));
        
        public static UserData Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sbjk")]
        public string userName_http_MES {
            get {
                return ((string)(this["userName_http_MES"]));
            }
            set {
                this["userName_http_MES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sbjk2018")]
        public string password_http_MES {
            get {
                return ((string)(this["password_http_MES"]));
            }
            set {
                this["password_http_MES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2018")]
        public string site_http_MES {
            get {
                return ((string)(this["site_http_MES"]));
            }
            set {
                this["site_http_MES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("device")]
        public string userName_http_WMS {
            get {
                return ((string)(this["userName_http_WMS"]));
            }
            set {
                this["userName_http_WMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123456")]
        public string password_http_WMS {
            get {
                return ((string)(this["password_http_WMS"]));
            }
            set {
                this["password_http_WMS"] = value;
            }
        }
    }
}
