//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanUploader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class User_Http : global::System.Configuration.ApplicationSettingsBase {
        
        private static User_Http defaultInstance = ((User_Http)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new User_Http())));
        
        public static User_Http Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yfhp")]
        public string username_MES_hp {
            get {
                return ((string)(this["username_MES_hp"]));
            }
            set {
                this["username_MES_hp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123456")]
        public string password_MES_hp {
            get {
                return ((string)(this["password_MES_hp"]));
            }
            set {
                this["password_MES_hp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2018")]
        public string site_MES {
            get {
                return ((string)(this["site_MES"]));
            }
            set {
                this["site_MES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("test")]
        public string username_MES_cm {
            get {
                return ((string)(this["username_MES_cm"]));
            }
            set {
                this["username_MES_cm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123456")]
        public string password_MES_cm {
            get {
                return ((string)(this["password_MES_cm"]));
            }
            set {
                this["password_MES_cm"] = value;
            }
        }
    }
}
